server:
  port: 8082
spring.cloud.stream:
  kafka:
    binder:
      replication-factor: 1
  function:
    definition: paymentProcessor;inventoryEventConsumer;paymentSupplier
  bindings:
    paymentProcessor-in-0:
      destination: order-event
    paymentProcessor-out-0:
      destination: payment-event
    inventoryEventConsumer-in-0:
      destination: inventory-event
    paymentSupplier-out-0:
      destination: payment-event
