server:
  port: 8080
spring.cloud.stream:
  kafka:
    binder:
      replication-factor: 1
  function:
    definition: orderSupplier;shippingEventConsumer;inventoryOutOfStockEventConsumer
  bindings:
    orderSupplier-out-0:
      destination: order-event
#    orderConfirmedSupplier-out-0:
#      destination: order-confirmed-event
    shippingEventConsumer-in-0:
      destination: shipping-event
    inventoryOutOfStockEventConsumer-in-0:
      destination: inventory-out-of-stock-event

#      producer:
#        partition-key-expression: headers['partitionKey']
#        partition-count: 12
#        replication:
#          factor: 1