server:
  port: 8080
spring.cloud.stream:
  kafka:
    binder:
      replication-factor: 1
  function:
    definition: orderSupplier;orderConfirmedSupplier;paymentEventConsumer;inventoryEventConsumer;shippingEventConsumer
  bindings:
    orderSupplier-out-0:
      destination: order-event
    orderConfirmedSupplier-out-0:
      destination: order-confirmed-event
    paymentEventConsumer-in-0:
      destination: payment-event
    inventoryEventConsumer-in-0:
      destination: inventory-event
    shippingEventConsumer-in-0:
      destination: shipping-event

#      producer:
#        partition-key-expression: headers['partitionKey']
#        partition-count: 12
#        replication:
#          factor: 1