server:
  port: 8081
spring.cloud.stream:
  kafka:
    binder:
      replication-factor: 1
  function:
    definition: inventoryConsumer;inventorySupplier;inventoryOutOfStockSupplier
  bindings:
    inventoryConsumer-in-0:
      destination: order-event
    inventorySupplier-out-0:
      destination: inventory-event
    inventoryOutOfStockSupplier-out-0:
      destination: inventory-out-of-stock-event
